spring:
  output.ansi.enabled: always  #add terminal color
  h2: # h2 console
    console:
      path: /h2-console
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
  profile:
    include: oauth, real-db
  jpa:
    properties:
      hibernet:
        ddl-auto: none
    show_sql: false
  session:
    store-type: jdbc
#  datasource:
#    hikari:
#      jdbc-url: jdbc:mariadb://productresell.cylyv0ufwnpb.ap-northeast-2.rds.amazonaws.com:3306/ProductResell
#      username: admin
#      password: Product1!
#      driver-class-name: org.mariadb.jdbc.Driver





