spring:
  output.ansi.enabled: always  #add terminal color
  h2: # h2 console
    console:
      path: /h2-console
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
  jpa.show_sql: true





